# mysql cluster in Single-Primary Mode
# run 1 master and 2 slave replicas


volumes:
  mysql_master_volume:
  mysql_first_slave_volume:
  mysql_second_slave_volume:

networks:
  db:

services:
  mysql-master:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql_master_volume:/var/lib/mysql
      - ./master.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: pass
    networks:
      - db


  mysql-slave1:
    image: mysql
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - mysql_first_slave_volume:/var/lib/mysql
      - ./slave.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: pass
    networks:
      - db
    depends_on:
      - mysql-master

  mysql-slave2:
    image: mysql
    ports:
      - "3308:3306"
    restart: always
    volumes:
      - mysql_second_slave_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: pass
    networks:
      - db
    depends_on:
      - mysql-master